### PR TITLE
fixed floating point error

### PR DESCRIPTION
**Pull request by giannamars**
I fixed a rounding error in the calculation of NOSC, as well as for stoichAnStar_O2.

### CODE REVIEW

**Comment by coldfire79** [comment]
Thank you for your interest in this app. Would you please give me more information about your error? If you just want to explicitly use the compositions as floating values, it'd better to explicitly cast all the compositions in __init__ function.

**Comment by giannamars** [comment]
> Thank you for your interest in this app. Would you please give me more information about your error? If you just want to explicitly use the compositions as floating values, it'd better to explicitly cast all the compositions in **init** function.

a = int
nosc = -ne/a+4 will give a rounding error
same in stoichAnStar_O2 = stoichAnStarB+(1/a)*stoich_electron_donor

**Comment by coldfire79** [comment]
No worries. When dividing an integer by another integer in Python 3, the division operation x / y represents a true division (uses __truediv__ method) and automatically produces a floating point result without any rounding errors. Please refer to [PEP 238](https://www.python.org/dev/peps/pep-0238/) for the details. If you agree, I'll close this issue.

**Comment by giannamars** [comment]
> No worries. When dividing an integer by another integer in Python 3, the division operation x / y represents a true division (uses **truediv** method) and automatically produces a floating point result without any rounding errors. Please refer to [PEP 238](https://www.python.org/dev/peps/pep-0238/) for the details. If you agree, I'll close this issue.


**edit** I'm on Python 2.7. It seems to give the correct result with Python 3. Thanks for looking into it! The issue can be closed.

I have attached a minimal example for one compound, where NOSC should evaluate to -0.5, but evaluates to -1.0, because of a rounding error (-18/4+4 is not equal to -18.0/4.0 +4.0) for some reason. 


import ThermoStoichiometry as TS

el = 'C4H9NO2'
a = TS.ThermoStoichiometry(el)
chemical_composition = a.extract_composition()

a = chemical_composition['C']
b = chemical_composition['H']
c = chemical_composition['N']
d = chemical_composition['O']
e = chemical_composition['S']
f = chemical_composition['P']
z = 0

ne = -z+4*a+b-3*c-2*d+5*e-2*f  # number of electrons transferred in D 
nosc = -ne/a+4                 # evaulates to -1.0, but should be -0.5 -18/4+4
#nosc = -(ne/float(a)) + 4     #  evaulates to -0.5

**Comment by coldfire79** [comment]
I think you tried to use my old code to parse the compositions from the formula. But anyway it's perfectly working well. Please check your python version, which should be >3.
And since this is for the KBase app, all package should run in the docker container. 
If you want to keep using python 2, you can use the following line.
```python
from __future__ import division
```

**Pull request closed without merging**
